# Generated by Django 3.1.3 on 2020-12-01 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='resumeAuthorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumeName', models.CharField(max_length=10000)),
                ('dateOfCreation', models.DateField()),
                ('token', models.CharField(max_length=10000000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='workExpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=1000)),
                ('role', models.CharField(max_length=1000)),
                ('designation', models.CharField(max_length=1000)),
                ('startingDate', models.DateField()),
                ('endingDate', models.DateField()),
                ('description', models.CharField(max_length=100000)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='resume.resumeauthormodel')),
            ],
        ),
        migrations.CreateModel(
            name='skillsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfSkill', models.CharField(max_length=10000)),
                ('selfRating', models.IntegerField(max_length=1000)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='resume.resumeauthormodel')),
            ],
        ),
        migrations.CreateModel(
            name='awardsAchievementHobbiesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfaward', models.CharField(max_length=10000)),
                ('description', models.CharField(max_length=100000)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='resume.resumeauthormodel')),
            ],
        ),
        migrations.CreateModel(
            name='additionalDetailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=10000)),
                ('contactNumber', models.IntegerField(max_length=10000)),
                ('first_name', models.CharField(max_length=10000)),
                ('last_name', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('profilePic', models.FileField(upload_to='profilePics/')),
                ('selfDescription', models.CharField(max_length=100000000)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='resume.resumeauthormodel')),
            ],
        ),
        migrations.CreateModel(
            name='academicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutionName', models.CharField(max_length=1000)),
                ('degreeType', models.CharField(max_length=1000)),
                ('degreeName', models.CharField(max_length=1000)),
                ('startingDate', models.DateField()),
                ('endingDate', models.DateField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='resume.resumeauthormodel')),
            ],
        ),
    ]
