# Generated by Django 3.1.3 on 2020-12-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resumetemplatesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaldetailsmodel',
            name='contactNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='skillsmodel',
            name='selfRating',
            field=models.IntegerField(),
        ),
    ]
